/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvanceDto {
  dateEnregistrement: string | null;
  duree: number | null;
  id?: number;
  membreId: number | null;
  montantCapital: number;
}
