/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CotisationDto {
  dateCotisation: string | null;
  id?: number;
  membreId: number;
  montant: number;
}
