/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EcheanceDto {
  avanceId?: number | null;
  creditId?: number | null;
  dateEcheance: string | null;
  id?: number;
  montantCapital: number;
  montantInterets?: number;
}
