/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EcritureDto {
  dateEnregistrement: string | null;
  id?: number;
  libelle: string | null;
  mouvementId: number | null;
}
