/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NullableOfSexe } from '../models/nullable-of-sexe';
export interface MembreDto {
  agenceId: number | null;
  dateAdhesion: string | null;
  dateNaissance: string | null;
  email: string | null;
  estActif?: boolean | null;
  id?: number;
  lieuNaissance: string | null;
  nom: string | null;
  photo?: string | null;
  sexe: NullableOfSexe | null;
  telephone: string | null;
}
