/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MouvementDto {
  avanceId?: number | null;
  cotisationId?: number | null;
  creditId?: number | null;
  dateMouvement: string | null;
  echeanceId?: number | null;
  id?: number;
  libelle: string | null;
  membreId?: number | null;
  montantCredit: number;
  montantDebit: number;
}
