/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MouvementComptableDto {
  compteId: number | null;
  ecritureId: number | null;
  id?: number;
  montantCredit: number;
  montantDebit: number;
}
