/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OperationDto {
  compteId: number | null;
  gabaritId: number | null;
  id?: number;
  montantCredit: number;
  montantDebit: number;
  montantFixe: boolean | null;
}
