/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NullableOfRole } from '../models/nullable-of-role';
export interface UtilisateurDto {
  estActif?: boolean | null;
  id?: number;
  login?: string | null;
  photo?: string | null;
  role?: NullableOfRole | null;
}
