// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mutuelleApi.data;

#nullable disable

namespace mutuelleApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250727041558_update_database_3")]
    partial class update_database_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mutuelleApi.models.Adhesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateAdhesion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.ToTable("Adhesions");
                });

            modelBuilder.Entity("mutuelleApi.models.Agence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agences");
                });

            modelBuilder.Entity("mutuelleApi.models.Avance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateDecaissement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDemande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("MontantCapital")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.ToTable("Avances");
                });

            modelBuilder.Entity("mutuelleApi.models.Cotisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateCotisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("Salaire")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.ToTable("Cotisations");
                });

            modelBuilder.Entity("mutuelleApi.models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateDecaissement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDemande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("MontantCapital")
                        .HasColumnType("float");

                    b.Property<double>("MontantCommission")
                        .HasColumnType("float");

                    b.Property<double>("MontantInterets")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("mutuelleApi.models.Echeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvanceId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditId")
                        .HasColumnType("int");

                    b.Property<string>("DateAnticipation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEcheance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("MontantCapital")
                        .HasColumnType("float");

                    b.Property<double>("MontantCommission")
                        .HasColumnType("float");

                    b.Property<double>("MontantInterets")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AvanceId");

                    b.HasIndex("CreditId");

                    b.ToTable("Echeances");
                });

            modelBuilder.Entity("mutuelleApi.models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenceId")
                        .HasColumnType("int");

                    b.Property<string>("DateAdhesion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgenceId");

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("mutuelleApi.models.Mouvement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdhesionId")
                        .HasColumnType("int");

                    b.Property<int?>("AvanceId")
                        .HasColumnType("int");

                    b.Property<int?>("CotisationId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditId")
                        .HasColumnType("int");

                    b.Property<string>("DateMouvement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EcheanceId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<double>("MontantCredit")
                        .HasColumnType("float");

                    b.Property<double>("MontantDebit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AdhesionId")
                        .IsUnique()
                        .HasFilter("[AdhesionId] IS NOT NULL");

                    b.HasIndex("AvanceId")
                        .IsUnique()
                        .HasFilter("[AvanceId] IS NOT NULL");

                    b.HasIndex("CotisationId")
                        .IsUnique()
                        .HasFilter("[CotisationId] IS NOT NULL");

                    b.HasIndex("CreditId");

                    b.HasIndex("EcheanceId");

                    b.HasIndex("MembreId");

                    b.ToTable("Mouvements");
                });

            modelBuilder.Entity("mutuelleApi.models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ClesMotDePasse")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<byte[]>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("mutuelleApi.models.Adhesion", b =>
                {
                    b.HasOne("mutuelleApi.models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("mutuelleApi.models.Avance", b =>
                {
                    b.HasOne("mutuelleApi.models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("mutuelleApi.models.Cotisation", b =>
                {
                    b.HasOne("mutuelleApi.models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("mutuelleApi.models.Credit", b =>
                {
                    b.HasOne("mutuelleApi.models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("mutuelleApi.models.Echeance", b =>
                {
                    b.HasOne("mutuelleApi.models.Avance", "Avance")
                        .WithMany("Echeancier")
                        .HasForeignKey("AvanceId");

                    b.HasOne("mutuelleApi.models.Credit", "Credit")
                        .WithMany("Echeancier")
                        .HasForeignKey("CreditId");

                    b.Navigation("Avance");

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("mutuelleApi.models.Membre", b =>
                {
                    b.HasOne("mutuelleApi.models.Agence", "Agence")
                        .WithMany()
                        .HasForeignKey("AgenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");
                });

            modelBuilder.Entity("mutuelleApi.models.Mouvement", b =>
                {
                    b.HasOne("mutuelleApi.models.Adhesion", null)
                        .WithOne("Mouvement")
                        .HasForeignKey("mutuelleApi.models.Mouvement", "AdhesionId");

                    b.HasOne("mutuelleApi.models.Avance", null)
                        .WithOne("Mouvement")
                        .HasForeignKey("mutuelleApi.models.Mouvement", "AvanceId");

                    b.HasOne("mutuelleApi.models.Cotisation", null)
                        .WithOne("Mouvement")
                        .HasForeignKey("mutuelleApi.models.Mouvement", "CotisationId");

                    b.HasOne("mutuelleApi.models.Credit", null)
                        .WithMany("Mouvements")
                        .HasForeignKey("CreditId");

                    b.HasOne("mutuelleApi.models.Echeance", null)
                        .WithMany("Mouvements")
                        .HasForeignKey("EcheanceId");

                    b.HasOne("mutuelleApi.models.Membre", null)
                        .WithMany("Mouvements")
                        .HasForeignKey("MembreId");
                });

            modelBuilder.Entity("mutuelleApi.models.Adhesion", b =>
                {
                    b.Navigation("Mouvement");
                });

            modelBuilder.Entity("mutuelleApi.models.Avance", b =>
                {
                    b.Navigation("Echeancier");

                    b.Navigation("Mouvement");
                });

            modelBuilder.Entity("mutuelleApi.models.Cotisation", b =>
                {
                    b.Navigation("Mouvement");
                });

            modelBuilder.Entity("mutuelleApi.models.Credit", b =>
                {
                    b.Navigation("Echeancier");

                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("mutuelleApi.models.Echeance", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("mutuelleApi.models.Membre", b =>
                {
                    b.Navigation("Mouvements");
                });
#pragma warning restore 612, 618
        }
    }
}
