/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AgenceService } from './services/agence.service';
import { AuthService } from './services/auth.service';
import { AvanceService } from './services/avance.service';
import { CompteService } from './services/compte.service';
import { CotisationService } from './services/cotisation.service';
import { CreditControlerService } from './services/credit-controler.service';
import { EcheanceService } from './services/echeance.service';
import { EcritureService } from './services/ecriture.service';
import { GabaritService } from './services/gabarit.service';
import { MembreService } from './services/membre.service';
import { MouvementComptableService } from './services/mouvement-comptable.service';
import { MouvementService } from './services/mouvement.service';
import { OperationService } from './services/operation.service';
import { UtilisateurService } from './services/utilisateur.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AgenceService,
    AuthService,
    AvanceService,
    CompteService,
    CotisationService,
    CreditControlerService,
    EcheanceService,
    EcritureService,
    GabaritService,
    MembreService,
    MouvementComptableService,
    MouvementService,
    OperationService,
    UtilisateurService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
