/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AgenceDto } from './models/agence-dto';
export type { AuthRequestDto } from './models/auth-request-dto';
export type { AvanceDto } from './models/avance-dto';
export type { CompteDto } from './models/compte-dto';
export type { CotisationDto } from './models/cotisation-dto';
export type { CreditDto } from './models/credit-dto';
export type { EcheanceDto } from './models/echeance-dto';
export type { EcritureDto } from './models/ecriture-dto';
export type { GabaritDto } from './models/gabarit-dto';
export type { IFormFile } from './models/i-form-file';
export type { MembreDto } from './models/membre-dto';
export type { MouvementComptableDto } from './models/mouvement-comptable-dto';
export type { MouvementDto } from './models/mouvement-dto';
export type { NullableOfRole } from './models/nullable-of-role';
export type { NullableOfSexe } from './models/nullable-of-sexe';
export type { OperationDto } from './models/operation-dto';
export type { UtilisateurDto } from './models/utilisateur-dto';
