/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAgenceAddPost } from '../fn/agence/api-agence-add-post';
import { ApiAgenceAddPost$Params } from '../fn/agence/api-agence-add-post';
import { apiAgenceGet } from '../fn/agence/api-agence-get';
import { ApiAgenceGet$Params } from '../fn/agence/api-agence-get';
import { apiAgenceIdDelete } from '../fn/agence/api-agence-id-delete';
import { ApiAgenceIdDelete$Params } from '../fn/agence/api-agence-id-delete';
import { apiAgenceIdPut } from '../fn/agence/api-agence-id-put';
import { ApiAgenceIdPut$Params } from '../fn/agence/api-agence-id-put';

@Injectable({ providedIn: 'root' })
export class AgenceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAgenceAddPost()` */
  static readonly ApiAgenceAddPostPath = '/api/Agence/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAgenceAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAgenceAddPost$Response(params: ApiAgenceAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAgenceAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAgenceAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAgenceAddPost(params: ApiAgenceAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiAgenceAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAgenceIdPut()` */
  static readonly ApiAgenceIdPutPath = '/api/Agence/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAgenceIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAgenceIdPut$Response(params: ApiAgenceIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAgenceIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAgenceIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAgenceIdPut(params: ApiAgenceIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiAgenceIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAgenceIdDelete()` */
  static readonly ApiAgenceIdDeletePath = '/api/Agence/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAgenceIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAgenceIdDelete$Response(params: ApiAgenceIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAgenceIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAgenceIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAgenceIdDelete(params: ApiAgenceIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiAgenceIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAgenceGet()` */
  static readonly ApiAgenceGetPath = '/api/Agence';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAgenceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAgenceGet$Response(params?: ApiAgenceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAgenceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAgenceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAgenceGet(params?: ApiAgenceGet$Params, context?: HttpContext): Observable<void> {
    return this.apiAgenceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
