/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAvanceAddPost } from '../fn/avance/api-avance-add-post';
import { ApiAvanceAddPost$Params } from '../fn/avance/api-avance-add-post';
import { apiAvanceGet } from '../fn/avance/api-avance-get';
import { ApiAvanceGet$Params } from '../fn/avance/api-avance-get';
import { apiAvanceIdDelete } from '../fn/avance/api-avance-id-delete';
import { ApiAvanceIdDelete$Params } from '../fn/avance/api-avance-id-delete';
import { apiAvanceIdPut } from '../fn/avance/api-avance-id-put';
import { ApiAvanceIdPut$Params } from '../fn/avance/api-avance-id-put';

@Injectable({ providedIn: 'root' })
export class AvanceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAvanceAddPost()` */
  static readonly ApiAvanceAddPostPath = '/api/Avance/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAvanceAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAvanceAddPost$Response(params: ApiAvanceAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAvanceAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAvanceAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAvanceAddPost(params: ApiAvanceAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiAvanceAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAvanceIdPut()` */
  static readonly ApiAvanceIdPutPath = '/api/Avance/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAvanceIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAvanceIdPut$Response(params: ApiAvanceIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAvanceIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAvanceIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAvanceIdPut(params: ApiAvanceIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiAvanceIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAvanceIdDelete()` */
  static readonly ApiAvanceIdDeletePath = '/api/Avance/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAvanceIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAvanceIdDelete$Response(params: ApiAvanceIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAvanceIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAvanceIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAvanceIdDelete(params: ApiAvanceIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiAvanceIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAvanceGet()` */
  static readonly ApiAvanceGetPath = '/api/Avance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAvanceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAvanceGet$Response(params?: ApiAvanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAvanceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAvanceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAvanceGet(params?: ApiAvanceGet$Params, context?: HttpContext): Observable<void> {
    return this.apiAvanceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
