/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCompteAddPost } from '../fn/compte/api-compte-add-post';
import { ApiCompteAddPost$Params } from '../fn/compte/api-compte-add-post';
import { apiCompteGet } from '../fn/compte/api-compte-get';
import { ApiCompteGet$Params } from '../fn/compte/api-compte-get';
import { apiCompteIdDelete } from '../fn/compte/api-compte-id-delete';
import { ApiCompteIdDelete$Params } from '../fn/compte/api-compte-id-delete';
import { apiCompteIdPut } from '../fn/compte/api-compte-id-put';
import { ApiCompteIdPut$Params } from '../fn/compte/api-compte-id-put';

@Injectable({ providedIn: 'root' })
export class CompteService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCompteAddPost()` */
  static readonly ApiCompteAddPostPath = '/api/Compte/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCompteAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCompteAddPost$Response(params: ApiCompteAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCompteAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCompteAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCompteAddPost(params: ApiCompteAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCompteAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCompteIdPut()` */
  static readonly ApiCompteIdPutPath = '/api/Compte/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCompteIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCompteIdPut$Response(params: ApiCompteIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCompteIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCompteIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCompteIdPut(params: ApiCompteIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiCompteIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCompteIdDelete()` */
  static readonly ApiCompteIdDeletePath = '/api/Compte/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCompteIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCompteIdDelete$Response(params: ApiCompteIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCompteIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCompteIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCompteIdDelete(params: ApiCompteIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiCompteIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCompteGet()` */
  static readonly ApiCompteGetPath = '/api/Compte';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCompteGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCompteGet$Response(params?: ApiCompteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCompteGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCompteGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCompteGet(params?: ApiCompteGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCompteGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
