/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCotisationAddPost } from '../fn/cotisation/api-cotisation-add-post';
import { ApiCotisationAddPost$Params } from '../fn/cotisation/api-cotisation-add-post';
import { apiCotisationGet } from '../fn/cotisation/api-cotisation-get';
import { ApiCotisationGet$Params } from '../fn/cotisation/api-cotisation-get';
import { apiCotisationIdDelete } from '../fn/cotisation/api-cotisation-id-delete';
import { ApiCotisationIdDelete$Params } from '../fn/cotisation/api-cotisation-id-delete';
import { apiCotisationIdPut } from '../fn/cotisation/api-cotisation-id-put';
import { ApiCotisationIdPut$Params } from '../fn/cotisation/api-cotisation-id-put';

@Injectable({ providedIn: 'root' })
export class CotisationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCotisationAddPost()` */
  static readonly ApiCotisationAddPostPath = '/api/Cotisation/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCotisationAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCotisationAddPost$Response(params: ApiCotisationAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCotisationAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCotisationAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCotisationAddPost(params: ApiCotisationAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCotisationAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCotisationIdPut()` */
  static readonly ApiCotisationIdPutPath = '/api/Cotisation/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCotisationIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCotisationIdPut$Response(params: ApiCotisationIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCotisationIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCotisationIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCotisationIdPut(params: ApiCotisationIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiCotisationIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCotisationIdDelete()` */
  static readonly ApiCotisationIdDeletePath = '/api/Cotisation/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCotisationIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCotisationIdDelete$Response(params: ApiCotisationIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCotisationIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCotisationIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCotisationIdDelete(params: ApiCotisationIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiCotisationIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCotisationGet()` */
  static readonly ApiCotisationGetPath = '/api/Cotisation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCotisationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCotisationGet$Response(params?: ApiCotisationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCotisationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCotisationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCotisationGet(params?: ApiCotisationGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCotisationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
