/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCreditControlerAddPost } from '../fn/credit-controler/api-credit-controler-add-post';
import { ApiCreditControlerAddPost$Params } from '../fn/credit-controler/api-credit-controler-add-post';
import { apiCreditControlerGet } from '../fn/credit-controler/api-credit-controler-get';
import { ApiCreditControlerGet$Params } from '../fn/credit-controler/api-credit-controler-get';
import { apiCreditControlerIdDelete } from '../fn/credit-controler/api-credit-controler-id-delete';
import { ApiCreditControlerIdDelete$Params } from '../fn/credit-controler/api-credit-controler-id-delete';
import { apiCreditControlerIdPut } from '../fn/credit-controler/api-credit-controler-id-put';
import { ApiCreditControlerIdPut$Params } from '../fn/credit-controler/api-credit-controler-id-put';

@Injectable({ providedIn: 'root' })
export class CreditControlerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCreditControlerAddPost()` */
  static readonly ApiCreditControlerAddPostPath = '/api/CreditControler/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditControlerAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCreditControlerAddPost$Response(params: ApiCreditControlerAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCreditControlerAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditControlerAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCreditControlerAddPost(params: ApiCreditControlerAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCreditControlerAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCreditControlerIdPut()` */
  static readonly ApiCreditControlerIdPutPath = '/api/CreditControler/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditControlerIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCreditControlerIdPut$Response(params: ApiCreditControlerIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCreditControlerIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditControlerIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCreditControlerIdPut(params: ApiCreditControlerIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiCreditControlerIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCreditControlerIdDelete()` */
  static readonly ApiCreditControlerIdDeletePath = '/api/CreditControler/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditControlerIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditControlerIdDelete$Response(params: ApiCreditControlerIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCreditControlerIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditControlerIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditControlerIdDelete(params: ApiCreditControlerIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiCreditControlerIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCreditControlerGet()` */
  static readonly ApiCreditControlerGetPath = '/api/CreditControler';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCreditControlerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditControlerGet$Response(params?: ApiCreditControlerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCreditControlerGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCreditControlerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCreditControlerGet(params?: ApiCreditControlerGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCreditControlerGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
