/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEcheanceAddPost } from '../fn/echeance/api-echeance-add-post';
import { ApiEcheanceAddPost$Params } from '../fn/echeance/api-echeance-add-post';
import { apiEcheanceGet } from '../fn/echeance/api-echeance-get';
import { ApiEcheanceGet$Params } from '../fn/echeance/api-echeance-get';
import { apiEcheanceIdDelete } from '../fn/echeance/api-echeance-id-delete';
import { ApiEcheanceIdDelete$Params } from '../fn/echeance/api-echeance-id-delete';
import { apiEcheanceIdPut } from '../fn/echeance/api-echeance-id-put';
import { ApiEcheanceIdPut$Params } from '../fn/echeance/api-echeance-id-put';

@Injectable({ providedIn: 'root' })
export class EcheanceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEcheanceAddPost()` */
  static readonly ApiEcheanceAddPostPath = '/api/Echeance/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcheanceAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcheanceAddPost$Response(params: ApiEcheanceAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcheanceAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcheanceAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcheanceAddPost(params: ApiEcheanceAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiEcheanceAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcheanceIdPut()` */
  static readonly ApiEcheanceIdPutPath = '/api/Echeance/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcheanceIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcheanceIdPut$Response(params: ApiEcheanceIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcheanceIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcheanceIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcheanceIdPut(params: ApiEcheanceIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiEcheanceIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcheanceIdDelete()` */
  static readonly ApiEcheanceIdDeletePath = '/api/Echeance/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcheanceIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcheanceIdDelete$Response(params: ApiEcheanceIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcheanceIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcheanceIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcheanceIdDelete(params: ApiEcheanceIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiEcheanceIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcheanceGet()` */
  static readonly ApiEcheanceGetPath = '/api/Echeance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcheanceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcheanceGet$Response(params?: ApiEcheanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcheanceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcheanceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcheanceGet(params?: ApiEcheanceGet$Params, context?: HttpContext): Observable<void> {
    return this.apiEcheanceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
