/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEcritureAddPost } from '../fn/ecriture/api-ecriture-add-post';
import { ApiEcritureAddPost$Params } from '../fn/ecriture/api-ecriture-add-post';
import { apiEcritureGet } from '../fn/ecriture/api-ecriture-get';
import { ApiEcritureGet$Params } from '../fn/ecriture/api-ecriture-get';
import { apiEcritureIdDelete } from '../fn/ecriture/api-ecriture-id-delete';
import { ApiEcritureIdDelete$Params } from '../fn/ecriture/api-ecriture-id-delete';
import { apiEcritureIdPut } from '../fn/ecriture/api-ecriture-id-put';
import { ApiEcritureIdPut$Params } from '../fn/ecriture/api-ecriture-id-put';

@Injectable({ providedIn: 'root' })
export class EcritureService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEcritureAddPost()` */
  static readonly ApiEcritureAddPostPath = '/api/Ecriture/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcritureAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcritureAddPost$Response(params: ApiEcritureAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcritureAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcritureAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcritureAddPost(params: ApiEcritureAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiEcritureAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcritureIdPut()` */
  static readonly ApiEcritureIdPutPath = '/api/Ecriture/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcritureIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcritureIdPut$Response(params: ApiEcritureIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcritureIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcritureIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEcritureIdPut(params: ApiEcritureIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiEcritureIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcritureIdDelete()` */
  static readonly ApiEcritureIdDeletePath = '/api/Ecriture/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcritureIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcritureIdDelete$Response(params: ApiEcritureIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcritureIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcritureIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcritureIdDelete(params: ApiEcritureIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiEcritureIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiEcritureGet()` */
  static readonly ApiEcritureGetPath = '/api/Ecriture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEcritureGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcritureGet$Response(params?: ApiEcritureGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiEcritureGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEcritureGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEcritureGet(params?: ApiEcritureGet$Params, context?: HttpContext): Observable<void> {
    return this.apiEcritureGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
