/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiGabaritAddPost } from '../fn/gabarit/api-gabarit-add-post';
import { ApiGabaritAddPost$Params } from '../fn/gabarit/api-gabarit-add-post';
import { apiGabaritGet } from '../fn/gabarit/api-gabarit-get';
import { ApiGabaritGet$Params } from '../fn/gabarit/api-gabarit-get';
import { apiGabaritIdDelete } from '../fn/gabarit/api-gabarit-id-delete';
import { ApiGabaritIdDelete$Params } from '../fn/gabarit/api-gabarit-id-delete';
import { apiGabaritIdPut } from '../fn/gabarit/api-gabarit-id-put';
import { ApiGabaritIdPut$Params } from '../fn/gabarit/api-gabarit-id-put';

@Injectable({ providedIn: 'root' })
export class GabaritService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiGabaritAddPost()` */
  static readonly ApiGabaritAddPostPath = '/api/Gabarit/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGabaritAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGabaritAddPost$Response(params: ApiGabaritAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiGabaritAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGabaritAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGabaritAddPost(params: ApiGabaritAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiGabaritAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiGabaritIdPut()` */
  static readonly ApiGabaritIdPutPath = '/api/Gabarit/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGabaritIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGabaritIdPut$Response(params: ApiGabaritIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiGabaritIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGabaritIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGabaritIdPut(params: ApiGabaritIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiGabaritIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiGabaritIdDelete()` */
  static readonly ApiGabaritIdDeletePath = '/api/Gabarit/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGabaritIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGabaritIdDelete$Response(params: ApiGabaritIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiGabaritIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGabaritIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGabaritIdDelete(params: ApiGabaritIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiGabaritIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiGabaritGet()` */
  static readonly ApiGabaritGetPath = '/api/Gabarit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGabaritGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGabaritGet$Response(params?: ApiGabaritGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiGabaritGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGabaritGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGabaritGet(params?: ApiGabaritGet$Params, context?: HttpContext): Observable<void> {
    return this.apiGabaritGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
