/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiMembreAddPost } from '../fn/membre/api-membre-add-post';
import { ApiMembreAddPost$Params } from '../fn/membre/api-membre-add-post';
import { apiMembreGet } from '../fn/membre/api-membre-get';
import { ApiMembreGet$Params } from '../fn/membre/api-membre-get';
import { apiMembreIdDelete } from '../fn/membre/api-membre-id-delete';
import { ApiMembreIdDelete$Params } from '../fn/membre/api-membre-id-delete';
import { apiMembreIdPut } from '../fn/membre/api-membre-id-put';
import { ApiMembreIdPut$Params } from '../fn/membre/api-membre-id-put';

@Injectable({ providedIn: 'root' })
export class MembreService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiMembreAddPost()` */
  static readonly ApiMembreAddPostPath = '/api/Membre/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMembreAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMembreAddPost$Response(params: ApiMembreAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMembreAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMembreAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMembreAddPost(params: ApiMembreAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiMembreAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMembreIdPut()` */
  static readonly ApiMembreIdPutPath = '/api/Membre/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMembreIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMembreIdPut$Response(params: ApiMembreIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMembreIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMembreIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMembreIdPut(params: ApiMembreIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiMembreIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMembreIdDelete()` */
  static readonly ApiMembreIdDeletePath = '/api/Membre/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMembreIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMembreIdDelete$Response(params: ApiMembreIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMembreIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMembreIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMembreIdDelete(params: ApiMembreIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiMembreIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMembreGet()` */
  static readonly ApiMembreGetPath = '/api/Membre';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMembreGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMembreGet$Response(params?: ApiMembreGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMembreGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMembreGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMembreGet(params?: ApiMembreGet$Params, context?: HttpContext): Observable<void> {
    return this.apiMembreGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
