/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiMouvementComptableAddPost } from '../fn/mouvement-comptable/api-mouvement-comptable-add-post';
import { ApiMouvementComptableAddPost$Params } from '../fn/mouvement-comptable/api-mouvement-comptable-add-post';
import { apiMouvementComptableGet } from '../fn/mouvement-comptable/api-mouvement-comptable-get';
import { ApiMouvementComptableGet$Params } from '../fn/mouvement-comptable/api-mouvement-comptable-get';
import { apiMouvementComptableIdDelete } from '../fn/mouvement-comptable/api-mouvement-comptable-id-delete';
import { ApiMouvementComptableIdDelete$Params } from '../fn/mouvement-comptable/api-mouvement-comptable-id-delete';
import { apiMouvementComptableIdPut } from '../fn/mouvement-comptable/api-mouvement-comptable-id-put';
import { ApiMouvementComptableIdPut$Params } from '../fn/mouvement-comptable/api-mouvement-comptable-id-put';

@Injectable({ providedIn: 'root' })
export class MouvementComptableService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiMouvementComptableAddPost()` */
  static readonly ApiMouvementComptableAddPostPath = '/api/MouvementComptable/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementComptableAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementComptableAddPost$Response(params: ApiMouvementComptableAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementComptableAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementComptableAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementComptableAddPost(params: ApiMouvementComptableAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementComptableAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementComptableIdPut()` */
  static readonly ApiMouvementComptableIdPutPath = '/api/MouvementComptable/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementComptableIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementComptableIdPut$Response(params: ApiMouvementComptableIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementComptableIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementComptableIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementComptableIdPut(params: ApiMouvementComptableIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementComptableIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementComptableIdDelete()` */
  static readonly ApiMouvementComptableIdDeletePath = '/api/MouvementComptable/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementComptableIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementComptableIdDelete$Response(params: ApiMouvementComptableIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementComptableIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementComptableIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementComptableIdDelete(params: ApiMouvementComptableIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementComptableIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementComptableGet()` */
  static readonly ApiMouvementComptableGetPath = '/api/MouvementComptable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementComptableGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementComptableGet$Response(params?: ApiMouvementComptableGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementComptableGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementComptableGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementComptableGet(params?: ApiMouvementComptableGet$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementComptableGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
