/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiMouvementAddPost } from '../fn/mouvement/api-mouvement-add-post';
import { ApiMouvementAddPost$Params } from '../fn/mouvement/api-mouvement-add-post';
import { apiMouvementGet } from '../fn/mouvement/api-mouvement-get';
import { ApiMouvementGet$Params } from '../fn/mouvement/api-mouvement-get';
import { apiMouvementIdDelete } from '../fn/mouvement/api-mouvement-id-delete';
import { ApiMouvementIdDelete$Params } from '../fn/mouvement/api-mouvement-id-delete';
import { apiMouvementIdPut } from '../fn/mouvement/api-mouvement-id-put';
import { ApiMouvementIdPut$Params } from '../fn/mouvement/api-mouvement-id-put';

@Injectable({ providedIn: 'root' })
export class MouvementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiMouvementAddPost()` */
  static readonly ApiMouvementAddPostPath = '/api/Mouvement/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementAddPost$Response(params: ApiMouvementAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementAddPost(params: ApiMouvementAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementIdPut()` */
  static readonly ApiMouvementIdPutPath = '/api/Mouvement/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementIdPut$Response(params: ApiMouvementIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiMouvementIdPut(params: ApiMouvementIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementIdDelete()` */
  static readonly ApiMouvementIdDeletePath = '/api/Mouvement/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementIdDelete$Response(params: ApiMouvementIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementIdDelete(params: ApiMouvementIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiMouvementGet()` */
  static readonly ApiMouvementGetPath = '/api/Mouvement';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiMouvementGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementGet$Response(params?: ApiMouvementGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiMouvementGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiMouvementGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiMouvementGet(params?: ApiMouvementGet$Params, context?: HttpContext): Observable<void> {
    return this.apiMouvementGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
