/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiOperationAddPost } from '../fn/operation/api-operation-add-post';
import { ApiOperationAddPost$Params } from '../fn/operation/api-operation-add-post';
import { apiOperationGet } from '../fn/operation/api-operation-get';
import { ApiOperationGet$Params } from '../fn/operation/api-operation-get';
import { apiOperationIdDelete } from '../fn/operation/api-operation-id-delete';
import { ApiOperationIdDelete$Params } from '../fn/operation/api-operation-id-delete';
import { apiOperationIdPut } from '../fn/operation/api-operation-id-put';
import { ApiOperationIdPut$Params } from '../fn/operation/api-operation-id-put';

@Injectable({ providedIn: 'root' })
export class OperationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiOperationAddPost()` */
  static readonly ApiOperationAddPostPath = '/api/Operation/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOperationAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOperationAddPost$Response(params: ApiOperationAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOperationAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOperationAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOperationAddPost(params: ApiOperationAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiOperationAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiOperationIdPut()` */
  static readonly ApiOperationIdPutPath = '/api/Operation/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOperationIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOperationIdPut$Response(params: ApiOperationIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOperationIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOperationIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOperationIdPut(params: ApiOperationIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiOperationIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiOperationIdDelete()` */
  static readonly ApiOperationIdDeletePath = '/api/Operation/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOperationIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOperationIdDelete$Response(params: ApiOperationIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOperationIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOperationIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOperationIdDelete(params: ApiOperationIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiOperationIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiOperationGet()` */
  static readonly ApiOperationGetPath = '/api/Operation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOperationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOperationGet$Response(params?: ApiOperationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiOperationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOperationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOperationGet(params?: ApiOperationGet$Params, context?: HttpContext): Observable<void> {
    return this.apiOperationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
