/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUtilisateurAddImageIdPost } from '../fn/utilisateur/api-utilisateur-add-image-id-post';
import { ApiUtilisateurAddImageIdPost$Params } from '../fn/utilisateur/api-utilisateur-add-image-id-post';
import { apiUtilisateurAddPost } from '../fn/utilisateur/api-utilisateur-add-post';
import { ApiUtilisateurAddPost$Params } from '../fn/utilisateur/api-utilisateur-add-post';
import { apiUtilisateurGet } from '../fn/utilisateur/api-utilisateur-get';
import { ApiUtilisateurGet$Params } from '../fn/utilisateur/api-utilisateur-get';
import { apiUtilisateurIdDelete } from '../fn/utilisateur/api-utilisateur-id-delete';
import { ApiUtilisateurIdDelete$Params } from '../fn/utilisateur/api-utilisateur-id-delete';
import { apiUtilisateurIdPut } from '../fn/utilisateur/api-utilisateur-id-put';
import { ApiUtilisateurIdPut$Params } from '../fn/utilisateur/api-utilisateur-id-put';

@Injectable({ providedIn: 'root' })
export class UtilisateurService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUtilisateurAddPost()` */
  static readonly ApiUtilisateurAddPostPath = '/api/Utilisateur/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUtilisateurAddPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUtilisateurAddPost$Response(params: ApiUtilisateurAddPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUtilisateurAddPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUtilisateurAddPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUtilisateurAddPost(params: ApiUtilisateurAddPost$Params, context?: HttpContext): Observable<void> {
    return this.apiUtilisateurAddPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUtilisateurAddImageIdPost()` */
  static readonly ApiUtilisateurAddImageIdPostPath = '/api/Utilisateur/addImage/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUtilisateurAddImageIdPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUtilisateurAddImageIdPost$Response(params: ApiUtilisateurAddImageIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUtilisateurAddImageIdPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUtilisateurAddImageIdPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUtilisateurAddImageIdPost(params: ApiUtilisateurAddImageIdPost$Params, context?: HttpContext): Observable<void> {
    return this.apiUtilisateurAddImageIdPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUtilisateurIdPut()` */
  static readonly ApiUtilisateurIdPutPath = '/api/Utilisateur/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUtilisateurIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUtilisateurIdPut$Response(params: ApiUtilisateurIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUtilisateurIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUtilisateurIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUtilisateurIdPut(params: ApiUtilisateurIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiUtilisateurIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUtilisateurIdDelete()` */
  static readonly ApiUtilisateurIdDeletePath = '/api/Utilisateur/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUtilisateurIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUtilisateurIdDelete$Response(params: ApiUtilisateurIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUtilisateurIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUtilisateurIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUtilisateurIdDelete(params: ApiUtilisateurIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiUtilisateurIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUtilisateurGet()` */
  static readonly ApiUtilisateurGetPath = '/api/Utilisateur';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUtilisateurGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUtilisateurGet$Response(params?: ApiUtilisateurGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUtilisateurGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUtilisateurGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUtilisateurGet(params?: ApiUtilisateurGet$Params, context?: HttpContext): Observable<void> {
    return this.apiUtilisateurGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
